name: Learning Lab

on:
  issues:
    types: [opened]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue using Learning Lab
        uses: github/schools/learning-lab-components/issue-creator@v1.x
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          course-repo: "[jScolors]"
          course-owner: "[Rachael-Minage]"
          issue-title: "Start course"
